from .shopper_interface import ShopperInterface
from .digital_receipt_interface import DigitalReceiptInterface
from .factory_interface import FactoryInterface
from .pdf_reader_interface import PDFReaderInterface